---
title: "city_comps"
author: "Gillian McGinnis"
date: "12/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(wesanderson)
library(ggthemes)
```

```{r dataframes}
la_usa <- read_csv("data/la_no2.csv", skip=7) %>%
  mutate(city = "LA") %>%
  rename("mean" = 2) 
chi_usa <- read_csv("data/chi_no2.csv", skip=7) %>%
  mutate(city = "CHI") %>%
  rename("mean" = 2) 
mel_aus <- read_csv("data/mel_aus_no2.csv", skip=7) %>%
  mutate(city = "MEL") %>%
  rename("mean" = 2)
```


```{r wrangling}
joined <- full_join(la_usa, chi_usa) %>%
  full_join(mel_aus) %>%
  filter(mean > 0) %>%
  mutate(year = format(time, format="%Y"),
         month = format(time, format="%m"),
         day = format(time, format="%d"),
         m_d = format(time, format="%m-%d"),
         m_d_mod = as.Date(m_d, format="%m-%d"),
         d = as.Date(day, format="%d")) %>%
  mutate(year = format(time, format = "%Y"),
         y = as.Date(year, format = "%Y"),
         month = format(time, format = "%m"),
         m = as.Date(month, format = "%m"),
         day = format(time, format = "%d"),
         d = as.Date(day, format = "%d"),
         month_day = format(time, format="%m-%d"),
         m_d = as.Date(month_day, format="%m-%d")) %>%
  filter(year != "2018")
```

```{r viz}
ggplot(joined, aes(x = m_d, y = mean, color = year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_line(alpha=0.3)+
  #geom_point(alpha=0.3, shape = 1)+
  stat_smooth(se = FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")
```

```{r decade testing}
la_dec <- read_csv("data/la_no2_dec.csv", skip=7) %>%
  mutate(city = "LA") %>%
  rename("mean" = 2)

la_dec_df <- la_dec %>%
  filter(mean > 0) %>%
  mutate(year = format(time, format="%Y"),
         month = format(time, format="%m"),
         day = format(time, format="%d"),
         m_d = format(time, format="%m-%d"),
         m_d_mod = as.Date(m_d, format="%m-%d"),
         d = as.Date(day, format="%d")) %>%
  mutate(year = format(time, format = "%Y"),
         y = as.Date(year, format = "%Y"),
         month = format(time, format = "%m"),
         m = as.Date(month, format = "%m"),
         day = format(time, format = "%d"),
         d = as.Date(day, format = "%d"),
         month_day = format(time, format="%m-%d"),
         m_d = as.Date(month_day, format="%m-%d")) %>%
  mutate(year_cat = case_when(
    year == "2020" ~ "2020",
    #year != "2020" ~ "2010-2019"
    #year != c("2010", "2011", "2012", "2013", "2014", "2020") ~ "2015-2019",
    #year != c("2015", "2016", "2017", "2018", "2019", "2020") ~ "2010-2014"
    year == "2010" | year == "2011" | year == "2012" | year == "2013" | year == "2014" ~ "2010-2014",
    year == "2015" | year == "2016" | year == "2017" | year == "2018" | year == "2019" ~ "2015-2019"
  ))

ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_line(alpha=0.3)+
  #geom_point(alpha=0.3, shape = 1)+
  stat_smooth(se=FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")

## accidentally pretty graph
ggplot(la_dec_df, aes(x = m_d, y = mean, color = year))+
  #facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_line(alpha=0.3)+
  #geom_point(alpha=0.3, shape = 1)+
  stat_smooth(se=FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  scale_color_manual(values = wes_palette("Zissou1", 11, type = "continuous"))+
  labs(x = "Time", y = "Mean", color = "Year")


ggplot(la_dec_df, aes(x = m_d, y = mean, color = year))+
  #facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  #geom_line(alpha=0.3)+
  #geom_point(alpha=0.3, shape = 1)+
  geom_line(data = subset(la_dec_df, year != "2020"), alpha = 0.2)+
  geom_line(data = subset(la_dec_df, year == "2020"), alpha = 0.4)+
  # geom_point(data = subset(la_dec_df, year != "2020"), shape = 1, alpha = 0.3)+
  # geom_point(data = subset(la_dec_df, year == "2020"), alpha = 0.3)+
  stat_smooth(data = subset(la_dec_df, year != "2020"), se=FALSE)+
  stat_smooth(data = subset(la_dec_df, year == "2020"), se=FALSE, size=1.5)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  scale_color_manual(values = wes_palette("Zissou1", 11, type = "continuous"))+
  labs(x = "Time", y = "Mean", color = "Year")

my_pal <- wes_palette("Rushmore1")[3:5]
#the one
ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  geom_line(data = subset(la_dec_df, year != "2020"), alpha = 0.2)+
  geom_line(data = subset(la_dec_df, year == "2020"), alpha = 0.4)+
  stat_smooth(data = subset(la_dec_df, year != "2020"), se=FALSE)+
  stat_smooth(data = subset(la_dec_df, year == "2020"), se=FALSE, size=1.5)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  scale_color_manual(values = wes_palette("FantasticFox1", 3, type = "continuous"))+
  #scale_color_manual(values = my_pal)+
  #scale_color_manual(values = few_pal("Dark")(3))+
  labs(x = "Time", y = "Mean", color = "Year")




ggplot(la_dec_df, aes(x = m_d, y = mean, color = year))+
  #facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_point(data = subset(la_dec_df, year != "2020"), shape = 1, alpha = 0.3)+
  geom_point(data = subset(la_dec_df, year == "2020"), alpha = 0.3, color = "blue")+
  #stat_smooth(se=FALSE)+
  stat_smooth(data = subset(la_dec_df, year != "2020"), se=FALSE, alpha=0.7)+
  stat_smooth(data = subset(la_dec_df, year == "2020"), se=FALSE, color = "blue")+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  #scale_color_manual(values = wes_palette("Zissou1", 11, type = "continuous"))+
  labs(x = "Time", y = "Mean", color = "Year")

ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  #facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_point(data = subset(la_dec_df, year != "2020"), shape = 1, alpha = 0.2)+
  geom_point(data = subset(la_dec_df, year == "2020"), alpha = 0.3)+
  #stat_smooth(se=FALSE)+
  stat_smooth(data = subset(la_dec_df, year != "2020"), se=FALSE)+
  stat_smooth(data = subset(la_dec_df, year == "2020"), se=FALSE, size = 1.5)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  #scale_color_manual(values = wes_palette("Zissou1", 11, type = "continuous"))+
  labs(x = "Time", y = "Mean", color = "Year")

# la_dec_df_filtered <- la_dec_df %>%
#   filter(year %in% c("2015", "2016", "2017", "2018", "2019", "2020"))
# 
# ggplot(la_dec_df_filtered, aes(x = m_d, y = mean, color = year))+
#   #facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
#   geom_line(alpha=0.3)+
#   #geom_point(alpha=0.3, shape = 1)+
#   stat_smooth(se=FALSE)+
#   scale_x_date(date_breaks = "1 month", date_labels="%b")+
#   theme_few()+
#   theme(axis.text.x = element_text(angle = 30,
#                                    vjust = 0.7))+
#   #scale_color_manual(values = wes_palette("Zissou1", 11, type = "continuous"))+
#   scale_color_manual(values = wes_palette("Zissou1", 6, type = "continuous"))+
#   labs(x = "Time", y = "Mean", color = "Year")



ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_line(alpha=0.3)+
  #geom_point(alpha=0.3, shape = 1)+
  stat_smooth(se=FALSE, aes(color = year))+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")

ggplot(la_dec_df, aes(x = m_d, y = mean))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_line(data = subset(la_dec_df, year != "2020"), alpha=0.3)+
  stat_smooth(data = subset(la_dec_df, year != "2020"), se = FALSE, alpha=0.7,color = "black")+
  geom_line(data = subset(la_dec_df, year == "2020"), alpha = 0.7, color = "red")+
  stat_smooth(data = subset(la_dec_df, year == "2020"), se = FALSE, color = "red")+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")

ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_line(alpha=0.3)+
  stat_smooth(se=FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  #scale_color_manual(values = wes_palette("Zissou1", 2, type = "continuous"))+
  #scale_color_manual(values = wes_palette("Darjeeling1"))+
  labs(x = "Time", y = "Mean", color = "Year")

ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_point(data = subset(la_dec_df, year != "2020"), shape = 1, alpha = 0.2)+
  geom_line(data = subset(la_dec_df, year == "2020"), alpha = 0.5)+
  stat_smooth(se=FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")

ggplot(la_dec_df, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free")+
  geom_point(data = subset(la_dec_df, year != "2020"), shape = 1, alpha = 0.2)+
  geom_point(data = subset(la_dec_df, year == "2020"), alpha = 0.2)+
  stat_smooth(se=FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")
```

```{r}
joined_dec <- full_join(joined, la_dec_df) %>%
  mutate(year_cat = case_when(
    year == "2020" ~ "2020",
    #year != "2020" ~ "2010-2019"
    #year != c("2010", "2011", "2012", "2013", "2014", "2020") ~ "2015-2019",
    #year != c("2015", "2016", "2017", "2018", "2019", "2020") ~ "2010-2014"
    year == "2010" | year == "2011" | year == "2012" | year == "2013" | year == "2014" ~ "2010-2014",
    year == "2015" | year == "2016" | year == "2017" | year == "2018" | year == "2019" ~ "2015-2019"
  ))

ggplot(joined_dec, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  #geom_line(alpha = 0.5)+
  geom_point(data = subset(joined_dec, year != "2020"), shape = 1, alpha = 0.1)+
  geom_point(data = subset(joined_dec, year == "2020"), alpha = 0.1)+
  #geom_point(data = subset(joined_dec, year != "2020"), shape = 1, alpha = 0.2)+
  #geom_line(data = subset(joined_dec, year == "2020"), alpha = 0.5)+
  stat_smooth(se=FALSE)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  labs(x = "Time", y = "Mean", color = "Year")
```


```{r full city wrangling}
los_angeles <- read_csv("data/los_angeles.csv", skip=7)%>%
  mutate(city="Los Angeles")%>%
  rename("mean"=2)

london <- read_csv("data/london.csv", skip=7)%>%
  mutate(city="London")%>%
  rename("mean"=2)

beijing <- read_csv("data/beijing.csv", skip=7)%>%
  mutate(city="Beijing")%>%
  rename("mean"=2)

seoul <- read_csv("data/seoul.csv", skip=7)%>%
  mutate(city="Seoul")%>%
  rename("mean"=2)

milan <- read_csv("data/milan.csv", skip=7) %>%
  mutate(city="Milan")%>%
  rename("mean"=2)

city_sampling <- full_join(los_angeles, london) %>%
  full_join(beijing) %>%
  full_join(seoul) %>%
  full_join(milan) %>%
  filter(mean > 0) %>%
  mutate(year = format(time, format="%Y"),
         month = format(time, format="%m"),
         day = format(time, format="%d"),
         m_d = format(time, format="%m-%d"),
         m_d_mod = as.Date(m_d, format="%m-%d"),
         d = as.Date(day, format="%d")) %>%
  mutate(year = format(time, format = "%Y"),
         y = as.Date(year, format = "%Y"),
         month = format(time, format = "%m"),
         m = as.Date(month, format = "%m"),
         day = format(time, format = "%d"),
         d = as.Date(day, format = "%d"),
         month_day = format(time, format="%m-%d"),
         m_d = as.Date(month_day, format="%m-%d")) %>%
  mutate(year_cat = case_when(
    year == "2005" | year == "2006" | year == "2007" | year == "2008" | year == "2009" ~ "2005-2009",
    year == "2010" | year == "2011" | year == "2012" | year == "2013" | year == "2014" ~ "2010-2014",
    year == "2015" | year == "2016" | year == "2017" | year == "2018" | year == "2019" ~ "2015-2019",
    year == "2020" ~ "2020"
  )) %>%
  mutate(mean_mod = mean/(10e15))
```




```{r viz}
wes <- wes_palette("Rushmore1")[2:5]
#wes <- wes_palette("FantasticFox1")[2:5]
#the one
ggplot(city_sampling, aes(x = m_d, y = mean, color = year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  # geom_line(data = subset(city_sampling, year != "2020"), alpha = 0.2)+
  # geom_line(data = subset(city_sampling, year == "2020"), alpha = 0.4)+
  stat_smooth(data = subset(city_sampling, year != "2020"), se=FALSE)+
  stat_smooth(data = subset(city_sampling, year == "2020"), se=FALSE, size=1.5)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  #scale_color_manual(values = wes_palette("RUshmore1", 4, type = "continuous"))+
  scale_color_manual(values = wes)+
  #scale_color_manual(values = few_pal("Dark")(3))+
  labs(x = "Time", y = "Mean", color = "Year")



city_subset <- city_sampling %>%
  filter(year %in% c("2015", "2016", "2017", "2018", "2019", "2020"))

lab_mean <- expression(paste("Mean NO"[2]*" column density (10"^15*"molecules/cm"^2*")"))

city_subset$city <- factor(city_subset$city, levels = c("Los Angeles", "Beijing", "Seoul", "Milan", "London"))
sah_color <- wes_palette("Zissou1")[5]
sah_beijing <- as.Date("2020-01-23")
sah_los_angeles <- as.Date("2020-03-19")

ggplot(city_subset, aes(x = m_d, y = mean_mod, color = year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  # geom_line(data = subset(city_subset, year != "2020"), alpha = 0.2)+
  # geom_line(data = subset(city_subset, year == "2020"), alpha = 0.4)+
  # geom_point(data = subset(city_subset, year != "2020"), shape = 1, alpha = 0.2)+
  # geom_point(data = subset(city_subset, year == "2020"), alpha = 0.3)+
  # stat_smooth(data = subset(city_subset, year != "2020"), se=FALSE)+
  # stat_smooth(data = subset(city_subset, year == "2020"), se=FALSE, size=1.5)+
  #stat_smooth(alpha=0.1)+
  stat_smooth(se=FALSE)+
  geom_vline(data=filter(city_subset, city=="Beijing"), aes(xintercept=sah_beijing),color=sah_color)+
  geom_vline(data=filter(city_subset, city=="Los Angeles"), aes(xintercept=sah_los_angeles))+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  #theme_minimal()+
  #theme_economist_white()+
  theme_igray()+
  theme(legend.position="top")+
  #theme_economist()+
  # theme(axis.text.x = element_text(angle = 30,
  #                                  vjust = 0.7))+
  scale_color_manual(values = wes_palette("Zissou1", 6, type = "continuous"))+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year")

##HERE
#Source: https://en.wikipedia.org/wiki/COVID-19_pandemic_lockdowns
sah_dataframe <- city_subset %>%
  mutate(sah = case_when(
    city=="Los Angeles" ~ as.Date("2020-03-19"),
    city=="Beijing" ~ as.Date("2020-01-23"),
    #city=="Seoul" ~ as.Date("2020-01-01"), #South Korea did not enter lockdown
    city=="Milan" ~ as.Date("2020-03-09"),
    city=="London" ~ as.Date("2020-03-23")
  ))%>%
  mutate(sah_end = case_when(
    city=="Los Angeles" ~ as.Date("2020-05-08"),
    city=="Beijing" ~ as.Date("2020-03-25"),
    #city=="Seoul" ~ as.Date("2020-01-01"), #South Korea did not enter lockdown
    city=="Milan" ~ as.Date("2020-05-18"),
    city=="London" ~ as.Date("2020-07-04")
  ))

sah_labels <- sah_dataframe %>%
  mutate(yloc = case_when(
    city=="Los Angeles" ~ 0.65,
    city=="Beijing" ~ 1.75,
    #city=="Seoul" ~ 0, #South Korea did not enter lockdown
    city=="Milan" ~ 1.3,
    city=="London" ~ 0.8
  )) %>%
  mutate(yloc_end = case_when(
    city=="Los Angeles" ~ 0.65,
    city=="Beijing" ~ 1.75,
    #city=="Seoul" ~ 0, #South Korea did not enter lockdown
    city=="Milan" ~ 1.3,
    city=="London" ~ 0.8
  )) %>%
  select(city, sah, sah_end, yloc, yloc_end) %>%
  distinct() %>%
  mutate(sah_md = format(sah, format="%b %d"),
         sah_md_end = format(sah_end, format = "%b %d"))

ggplot(sah_dataframe, aes(x=m_d, y=mean_mod, color=year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  stat_smooth(se=FALSE)+
  geom_vline(aes(xintercept = sah), color=sah_color, linetype="dotted")+
  geom_vline(aes(xintercept = sah_end), color=sah_color, linetype="dotted")+
  #geom_blank(aes(fill=sah_color),show.legend=TRUE)+
  # scale_linetype(name="SAH")+
  # guides(linetype=guide_legend(override.aes=list(colour=sah_color)))+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_igray()+
  theme(legend.position="top", panel.grid.major.x=element_blank())+
  scale_color_manual(values = wes_palette("Zissou1", 6, type = "continuous"))+
  #geom_text(aes(x=sah, label=sah,y=max(mean_mod)),show.legend=FALSE,nudge_x=30)+
  ##geom_text(aes(x = sah, y = yloc, label = sah), color=sah_color, show.legend=TRUE,nudge_x=30)+
  geom_text(data=sah_labels,aes(x = sah, y = yloc, label = paste(sah_md)), size=3, color=sah_color, show.legend=FALSE, nudge_x=15)+
  geom_text(data=sah_labels,aes(x = sah_end, y = yloc_end, label = paste(sah_md_end)), size=3, color=sah_color, show.legend=FALSE, nudge_x=15)+
  #annotate("text", x = sah_dataframe$sah, y = 10, label="SAH")+
  #geom_vline(aes(xintercept = sah, color=sah_color), linetype="dotted")+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year")




##

ggplot(city_subset, aes(x = m_d, y = mean_mod, color = year, fill=year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  # geom_line(data = subset(city_subset, year != "2020"), alpha = 0.2)+
  # geom_line(data = subset(city_subset, year == "2020"), alpha = 0.4)+
  # geom_point(data = subset(city_subset, year != "2020"), shape = 1, alpha = 0.2)+
  # geom_point(data = subset(city_subset, year == "2020"), alpha = 0.3)+
  # stat_smooth(data = subset(city_subset, year != "2020"), se=FALSE)+
  # stat_smooth(data = subset(city_subset, year == "2020"), se=FALSE, size=1.5)+
  stat_smooth(alpha=0.1)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_igray()+
  theme(legend.position="top")+
  scale_color_manual(values = wes_palette("Zissou1", 6, type = "continuous"))+
  scale_fill_manual(values = wes_palette("Zissou1", 6, type = "continuous"))+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year", fill="Year")


ggplot(city_subset, aes(x = m_d, y = mean_mod, color = year, fill=year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  stat_smooth(data=subset(city_sampling, year_cat == "2005-2009"), aes(color=year_cat,fill=year_cat))+
  #geom_line(data=subset(city_sampling, year_cat == "2005-2009"), aes(color=year_cat),stat="smooth",linetype="longdash")+
  # geom_line(data = subset(city_subset, year != "2020"), alpha = 0.2)+
  # geom_line(data = subset(city_subset, year == "2020"), alpha = 0.4)+
  # geom_point(data = subset(city_subset, year != "2020"), shape = 1, alpha = 0.2)+
  # geom_point(data = subset(city_subset, year == "2020"), alpha = 0.3)+
  # stat_smooth(data = subset(city_subset, year != "2020"), se=FALSE)+
  # stat_smooth(data = subset(city_subset, year == "2020"), se=FALSE, size=1.5)+
  stat_smooth()+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_tufte()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  scale_color_manual(values = wes_palette("Zissou1", 7, type = "continuous"))+
  scale_fill_manual(values = wes_palette("Zissou1", 7, type = "continuous"))+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year", fill = "Year")

city_sampling$city <- factor(city_sampling$city, levels = c("Los Angeles", "Beijing", "Seoul", "Milan", "London"))
four_pal <- wes_palette("FantasticFox1")[2:5]
#four_pal <- wes_palette("Rushmore1")[2:5]

ggplot(city_sampling, aes(x = m_d, y = mean_mod, color = year_cat, fill=year_cat))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  stat_smooth(method="loess")+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_tufte()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  scale_color_manual(values = four_pal)+
  scale_fill_manual(values = four_pal)+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year", fill = "Year")

six_pal <- wes_palette("Zissou1", 6, type="continuous")

ggplot(data=subset(city_sampling, year_cat %in% c("2015-2019", "2020")), aes(x = m_d, y = mean_mod, color = year, fill=year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  stat_smooth(method="loess")+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  scale_color_manual(values = six_pal)+
  scale_fill_manual(values = six_pal)+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year", fill = "Year")
```

```{r}
city_subset <- city_sampling %>%
  filter(year %in% c("2015", "2016", "2017", "2018", "2019", "2020"))

lab_mean <- expression(paste("Mean NO"[2]*" column density (10"^15*"molecules/cm"^2*")"))

city_subset$city <- factor(city_subset$city, levels = c("Los Angeles", "Beijing", "Seoul", "Milan", "London"))
sah_color <- wes_palette("Zissou1")[5]


sah_all <- city_subset %>%
  mutate(sah1 = case_when(
    city=="Los Angeles" ~ as.Date("2020-03-19"),
    city=="Beijing" ~ as.Date("2020-01-23"),
    city=="Milan" ~ as.Date("2020-03-09"),
    city=="London" ~ as.Date("2020-03-23")
  ))%>%
  mutate(sah1_end = case_when(
    city=="Los Angeles" ~ as.Date("2020-05-08"),
    city=="Beijing" ~ as.Date("2020-03-25"),
    city=="Milan" ~ as.Date("2020-05-18"),
    city=="London" ~ as.Date("2020-07-04")
  ))%>%
  mutate(sah2 = case_when(
    city=="Milan" ~ as.Date("2020-11-06"),
    city=="London" ~ as.Date("2020-11-05")
  ))%>%
  mutate(sah2_end = case_when(
    city=="Milan" ~ as.Date("2020-12-03"),
    city=="London" ~ as.Date("2020-12-02")
  ))

sah_all_labels <- sah_all %>%
  mutate(yloc1 = case_when(
    city=="Los Angeles" ~ 0.65,
    city=="Beijing" ~ 1.75,
    city=="Milan" ~ 1.3,
    city=="London" ~ 0.8
  )) %>%
  mutate(yloc1_end = case_when(
    city=="Los Angeles" ~ 0.65,
    city=="Beijing" ~ 1.75,
    city=="Milan" ~ 1.3,
    city=="London" ~ 0.95
  )) %>%
 mutate(yloc2 = case_when(
    city=="Milan" ~ 0.75,
    city=="London" ~ 0.95
  )) %>%
  mutate(yloc2_end = case_when(
    city=="Milan" ~ 0.75,
    city=="London" ~ 0.95
  )) %>%
  select(city, sah1, sah1_end, sah2, sah2_end, yloc1, yloc1_end, yloc2, yloc2_end) %>%
  distinct() %>%
  mutate(sah1_md = format(sah1, format="%b %d"),
         sah1_md_end = format(sah1_end, format = "%b %d"),
         sah2_md = format(sah2, format="%b %d"),
         sah2_md_end = format(sah2_end, format = "%b %d"))

# sah_labels_long <- sah_all_labels %>%
#   pivot_longer(2:5, names_to = "sah_cat", values_to="sah_dates")%>%
#   pivot_longer(2:5, names_to = "sah_cat_y", values_to = "sah_y")

ggplot(sah_all, aes(x=m_d, y=mean_mod, color=year))+
  facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y")+
  stat_smooth(se=FALSE)+
  geom_vline(aes(xintercept = sah1), color=sah_color, linetype="dotted")+
  geom_vline(aes(xintercept = sah1_end), color=sah_color, linetype="dotted")+
  geom_vline(aes(xintercept = sah2), color=sah_color, linetype="dotted")+
  geom_vline(aes(xintercept = sah2_end), color=sah_color, linetype="dotted")+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_igray()+
  theme(legend.position="top", panel.grid.major.x=element_blank())+
  scale_color_manual(values = wes_palette("Zissou1", 6, type = "continuous"))+
  geom_text(data=sah_all_labels,aes(x = sah1, y = yloc1, label = paste("SaH1:\n",sah1_md)),
            #size=2.5, color=sah_color, show.legend=FALSE, nudge_x=3, hjust=0)+
            size=2.25, color=sah_color, nudge_x=1, hjust=0)+
  geom_text(data=sah_all_labels,aes(x = sah1_end, y = yloc1_end, label = paste("End:\n",sah1_md_end)),
            size=2.25, color=sah_color, nudge_x=1, hjust=0)+
  geom_text(data=sah_all_labels,aes(x = sah2, y = yloc2, label = paste("SaH2:\n",sah2_md)),
            size=2.25, color=sah_color, nudge_x=1, hjust=0)+
  geom_text(data=sah_all_labels,aes(x = sah2_end, y = yloc2_end, label = paste("End:\n",sah2_md_end)),
            size=2.25, color=sah_color, nudge_x=1, hjust=0)+
  labs(x = "Time (data taken daily)", y = lab_mean, color = "Year")
```


```{r los angeles}
formatted_la <- city_sampling %>%
  filter(city == "Los Angeles")

#la_pal <- c(wes_palette("Darjeeling1")[5], wes_palette("Darjeeling1")[4], wes_palette("Darjeeling1")[2], wes_palette("Darjeeling1")[1])
#la_pal <- wes_palette("Rushmore1")[2:5]
la_pal <- wes_palette("FantasticFox1")[2:5]
#the one
ggplot(formatted_la, aes(x = m_d, y = mean, color = year_cat))+
  geom_line(data = subset(formatted_la, year != "2020"), alpha = 0.3)+
  geom_line(data = subset(formatted_la, year == "2020"), alpha = 0.4)+
  stat_smooth(data = subset(formatted_la, year != "2020"), se=FALSE)+
  stat_smooth(data = subset(formatted_la, year == "2020"), se=FALSE, size=1.5)+
  scale_x_date(date_breaks = "1 month", date_labels="%b")+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))+
  #scale_color_manual(values = wes_palette("FantasticFox1", 4, type="continuous"))+
  scale_color_manual(values = la_pal)+
  #scale_color_manual(values = few_pal("Dark")(3))+
  labs(x = "Time", y = "Mean", color = "Year")
```


```{r country wrangling, eval = FALSE, include = FALSE}
# usa <- read_csv("usa_no2.csv", skip=7)%>%
#   mutate(country="USA")%>%
#   rename("mean"=2)
# 
# china <- read_csv("china_no2.csv", skip=7) %>%
#   mutate(country="China")%>%
#   rename("mean"=2)
# 
# world_data <- full_join(usa, china) %>%
#   filter(mean > 0) %>%
#   mutate(year = format(time, format="%Y"),
#          month = format(time, format="%m"),
#          day = format(time, format="%d"),
#          m_d = format(time, format="%m-%d"),
#          m_d_mod = as.Date(m_d, format="%m-%d"),
#          d = as.Date(day, format="%d")) %>%
#   mutate(year = format(time, format = "%Y"),
#          y = as.Date(year, format = "%Y"),
#          month = format(time, format = "%m"),
#          m = as.Date(month, format = "%m"),
#          day = format(time, format = "%d"),
#          d = as.Date(day, format = "%d"),
#          month_day = format(time, format="%m-%d"),
#          m_d = as.Date(month_day, format="%m-%d")) %>%
#   mutate(year_cat = case_when(
#     year == "2005" | year == "2006" | year == "2007" | year == "2008" | year == "2009" ~ "2005-2009",
#     year == "2010" | year == "2011" | year == "2012" | year == "2013" | year == "2014" ~ "2010-2014",
#     year == "2015" | year == "2016" | year == "2017" | year == "2018" | year == "2019" ~ "2015-2019",
#     year == "2020" ~ "2020"
#   ))
```


